project:
  type: book

book:
  title: "Perception of 3D Data Visualizations"
  author: "Tyler Wiederich"
  date: today
  chapters:
    - index.qmd
    - ch0-lit-review/one-last-start.qmd
    #- ch1-bar3d/writeups/index.qmd
    #- ch2-experiential-learning/manuscript/dissertation-copy.qmd
    #- ch3-heat3d/writeups/1-992-paper/index.qmd
    #- ch99-references.qmd

format:
  pdf:
    documentclass: nuthesis
    classoption: [phd]
    geometry: []
    include-in-header:
      - thesis-metadata.tex
    fig-align: center
    toc: false


bibliography: master-references.bib
