---
title: "Conclusion"
editor: 
  markdown: 
    wrap: sentence
---

This research provides some of the initial empirical findings on statistical graphics rendered in our physical world.
While prior work on 3D-printed charts is limited, the studies presented here examine how dimensionality affects estimation tasks using modern graphical testing, as well as how these visualization can be integrated into educational contexts.

In the first study, we partially replicated the work of @cleveland1984 to extend their foundational work in perceptual tasks to include the dimensionality of charts.
We asked participants to estimate ratios of stimuli when the marked bars were either adjacent or separated.
For evaluating dimensionality, we included 2D bar charts, digitally interactive 3D bar charts, and 3D printed bar charts.
We did not find any significant results indicating that 3D-printed charts were less accurate in ratio estimations than their digital counterparts.
However, we did detect an anchoring when there was separation between the pairs of stimuli.
This suggested that participants were using reference points with the input slider, which is a common phenomena in perception studies that require numerical estimations.
These findings suggest that design components of the charts may affect how people interact with the data.

Using a slightly altered design from our first study, we incorporated the graphics experiment as an experiential learning opportunity for students enrolled in the introductory statistics course at the University of Nebraska-Lincoln.
Students completed a series of reflections where they wrote from the perspective of participants in research to consumers of scientific knowledge.
While the experimental design was more complex that what is taught in introductory courses, students demonstrated the ability to identify design components, such as research questions, variables, and randomization.
Students seemed to enjoy the process of learning about the experiment, which indicates that similar graphics studies could be used in a similar manner.

In our final study, we shifted our attention to heat maps, where all three dimensions of the chart are meaningfully displaying a variable from the dataset.
The study was designed to evaluate ratio estimations for 2D, digitally interactive 3D, and 3D-printed heat maps across different ratios and underlying datasets.
Results from this study suggest that digital and physical 3D heat maps have lower error rates than 2D heat maps, with no significant differences detected between the two 3D heat maps.
These findings are consist with previous research comparing digital representations of 2D and 3D charts, where 3D charts tend to perform better with value estimations when the third dimension is not a decorative component.
We also found a significant interaction between dataset and ratio, which suggests that error rates are different depending on specific features within the data.
The findings from this study suggest that 3D charts, whether digital or physical, can better convey information over 2D charts.

Taken together, our results suggest that 3D-printed charts are a valid means of tangibly communicating data.
With respect to ratio estimations, we found that 3D-printed charts were on par with their digitally interactive 3D counterparts, and better than their 2D counterparts when all dimensions are mapped to variables in the dataset within the context of a heat map.
In written responses, students seemed to enjoy the process of interacting with the charts as part of an experiment, which suggests that active graphics research is a good opportunity for experiential learning.
While uncommon in practice, converting traditional data visualizations into 3D-printed charts may have more benefits than their current novelty.

This research represents some of the initial graphical testing in 3D-printed charts.
While our results suggest that this style of graphical rendering may provide some benefits over traditional 2D charts, there are many conditions that we were unable to test that are unique to the construction of 3D-printed charts.
Similar to WebGL interfaces, interactions with the natural environment could influence how information is extracted from physical charts, such as lighting, size, material.
These conditions could be investigated in further studies to provide suggestions with respect to the sensitivity of rendering conditions.
Additionally, many previous graphical studies caution about the effect of surrounding values and optical illusions when extracting information from charts.
Follow-up studies controlling for surrounding values would provide further insight into the differences between digital and physical chart renderings.
Lastly, measures of error are not the only criteria for what makes a good chart.
Future studies could include additional perceptual tasks, such as pattern recognition, value lookups, or spatial reasoning.
This research serves as the initial framework of bringing 3D-printed charts into modern graphical testing and promoting their usage beyond the novelty where they currently exist.
