{
  "hash": "cc5f63ee4be0d631d6f43b7540cc77c0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Graphical Perception of Heatmaps: Dimensionality, Medium, and Accuracy of Ratio Estimations\"\nbibliography: references.bib\n---\n\n::: {.cell}\n\n:::\n\n\n\n\n## Introduction\n\nIn the 20th century, advancements in technology made data visualizations increasingly more affordable and accessible to a broader population. The primary change in formal data visualizations was from hand-drawn charts to computer-rendered charts [@tukey1965], and with subsequent advances in color printing and available software have allowed for data visualizations to enter other mediums. These include the ability create virtual and physical charts that effectively use the 3-dimensional (3D) world around us with the novel use of 3D-printed charts. This newer type of visualization has gained a small amount of traction in recent years as a method of producing tangible charts [@stusakIfYourMind2016; @huExploringNewParadigms2015b; @huronMakingDataPhysical2023].\n\nIn many disciplines, 3D-printed visualizations have shown mixed or promising results compared to alternative rendering formats. Although a comprehensive review of 3D-printing in scientific fields is beyond the scope of this paper, we highlight several examples of its use for visualization. @katsioloudis2018 conducted a study with engineering students and found no statistically significant difference between computer-rendered and 3D-printed models when students were asked to draw a cross-section of a dodecahedron, suggesting similar levels of spatial understanding between digital and physical representations. In contrast, other applications have highlighted advantages of 3D-printed models. For example, @holloway2019 reported positive feedback from visually impaired individuals when 3D-printed maps were used to support navigation. Similarly, in clinical education, @muff2022 found that 3D-printed anatomical structures were well accepted alongside VR glasses and 3D computer renderings. As 3D-printed visualizations become increasingly common across scientific fields, we explore their potential use in communicating statistical graphics.\n\nAt this time, there are few studies that evaluate 3D-printed charts for the purpose of displaying statistical information [@jansen2013; @stusak2015; @stusakIfYourMind2016; @huExploringNewParadigms2015b]. This may in part be due to the cost of materials and rendering times as compared to charts produced on a computer. A single chart can take up to a day to print, limiting the ability to quickly produce visualizations. Additionally, there are few options for producing such charts from statistical software. In R, the `rgl` package [@rgl] can export STL files that can be used by 3D-printing software, and similarly for the `rayshader` package [@rayshader]. However, these options are not optimized for essential considerations required of 3D-printed charts, such as embossed labels. Given the nature of 3-dimensional data, viewing a 3D realization of statistical information in a 3D environment is a realistic scenario that could increase the ability for information extraction.\n\n### Literature Review\n\nUsing an identical dataset across multiple chart types does not ensure that the data is perceived in the same way [@cleveland1984; @hofmann2012; @vanderplas2020]. One of the main factors in this phenomenon is how data is encoded into the chart. These encodings include, but are not limited to, placement along axes, lengths, areas, volumes, and color scales. For example, bar charts and pie charts are two common visualizations that have long been the topic of debate [@eells1926; @croxton1927; @cleveland1984; @spence1989]. Bar charts are constructed with the encodings of length, position, and area. In contrast, pie charts make use of arc lengths, angles, and area. Inherently, the comparison of different chart types is a comparison of encodings due to the changes in how data is being displayed.\n\n@cleveland1984 noted that estimates involving numerical accuracy may decrease when increasing dimensionality of the encoding, although this was not formally tested in their experiments. Their reasoning was due to Stevens' power law, a mathematical formulation of how magnitudes are perceived given different stimuli sources [@stevens1986]. The general form of the law is $\\psi(I)=kI^\\alpha$, where $I$ is the magnitude of a stimulus, $\\psi(I)$ is the perceived magnitude, $k$ is a proportionality constant from the unit of the stimulus, and $\\alpha$ is the exponent from the type of stimuli used. Studies have estimated that lengths are perceived without bias (i.e., $\\alpha=1$), but areas and volumes tend to have skewed perceptions [@cleveland1984]. This indicates that lower-dimensional charts may perform better when readers are tasked with extracting numerical estimates from the chart, although this has been a topic of debate in the last several decades.\n\nThere are mixed results in regard to the use of 3D charts, mostly attributable to the use of the third dimension. When the extra dimension does not convey meaningful information, estimates of accuracy decrease and solution times increase as compared to equivalent 2D charts [@fisher1997; @zacks1998; @fischer2000]. The same increase in solution time is seen when the third dimension is utilized for displaying data, but can sometimes produce better error rates than 2D charts [@barfield1989; @kraus2020]. Additionally, when given the option of 2D or 3D charts for extracting numerical information, the 2D charts showed increased preference and confidence than their 3D counterparts [@barfield1989; @fisher1997]. It is worth noting that all of these studies use 2D or virtual reality renderings of 3D charts and not physical 3D charts.\n\nMany studies that assess 3D charts use computer-rendered displays that leverage high levels of precision in their output. Digital renderings allow for exact control over visual properties, whereas physical charts are subject to factors such as chart materials, lighting conditions, interactivity, and viewing distance. Some of these factors have already been suggested to have a measureable effect within computer renderings [@tarr2001; @wang2022]. While virtual reality can offer similar interactions with 3D objects compared to the real world, perceptual judgements can be distorted in virtual environments [@kelly2018; @park2021]. The result is that many findings for the perception of 3D statistical graphics are limited to the method in which they were rendered.\n\nTo date, few empirical studies have investigated 3D-printed charts, and it is unclear if they follow the framework of existing theories on data visualizations. One of the first studies to examine digital and physical renderings primarily focused on information retrieval times, where physical 3D heatmaps had lower completion times than digitized 2D and 3D alternatives [@jansen2013]. In their study, error rates were also collected, but had small effect sizes due to the 2D, digital 3D, and physical 3D charts. Other studies on physical statistical graphics tend to focus on bar charts, where the third dimension is not used for information. Physical 3D bar charts are suggested to have conditionally improved memorability, subject to specific datasets [@stusak2015; @stusakIfYourMind2016]. @huExploringNewParadigms2015b discussed the construction of 3D-printed bar charts with accessibility features, though these designs do not appear to have been empirically evaluated.\n\nWe hypothesize that 3D charts in 3D environments will produce better information extraction than their computer-rendered counterparts. Specifically, we compare 3D-printed charts to digital renderings of 2D static charts and 3D interactive charts. We suspect that this difference will hold across multiple data sets and different magnitudes of stimuli. In this paper, we evaluate the accuracy of numerical estimations on true 3D charts by conducting a factorial experiment that assessed chart types and ratios of pairs of stimuli. We discuss the construction of the stimuli and how we closely matched the charts to compare 2D, 3D-digital, and 3D-printed renderings of heatmap data.\n\n## Methods\n\nOur study was designed to evaluate and expand the literature on numerical estimation of dimensionality for 3D charts. In our study, we focused on 2D and 3D heatmaps, which we carefully constructed to ensure that differences can be attributed to the dimensionality of the chart and the mapping of data when comparing 2D to 3D. All of our data and methods are publicly available for open science and reproducibility at <https://github.com/TWiedRW/ch3-heat3d>. In this section, we discuss the process of designing our experiment and participant recruitment.\n\n### Stimuli\n\nWe define stimuli as the magnitude of our selected values. In a 3D Cartesian space, the X- and Y- axes represent the coordinates of the stimuli, and the Z-axis represents the value for the stimuli. Each X and Y coordinate is represented by a square tile with a 1:1 aspect ratio. In a 2D space, the Z variable is mapped to fill with a monochromatic gradient. All stimuli and remaining randomly generated values range between 0 and 100 units. In this experiment, $X=1, 2, \\dots,10$ and $Y=1, 2,\\dots,10$.\n\nOur experiment is designed using the method of constant stimuli, where comparisons between stimuli are with respect to a stimulus that remains the same magnitude [@kingdom2016 chap. 3]. We set the constant stimuli at 50 units. For stimuli between 50 and 100, we set the maximum stimuli value at 90 and equally partitioned the ratios of stimuli with the constant stimuli, $\\frac{50}{90}=0.556$ to $\\frac{50}{50}=1.0$, resulting in 4 varying stimuli values where 50 is the smallest value. The same ratios obtained with stimuli between 50 and 90 were used to create 4 stimuli varying between 0 and 50, where 50 is the largest value. Additionally, we also included a stimulus pair where both values are 50, resulting in nine total pairs of stimuli. All stimuli values can be found in @fig-stimuli-values.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload('../../data/stimuli.rda')\nstimuli %>% \n  ggplot(mapping = aes(x = pair_id, y = values)) + \n  geom_bar(stat = 'identity', width = 1, color = 'black', fill = '#1a80bb') + \n  geom_col(mapping = aes(y = 50), fill = '#ea801c', alpha = 1/3, width = 1/2) + \n  geom_text(aes(label = round(values, 1), y = 5)) + \n  theme_minimal() + \n  annotate('text', x = 5, y = 25, label = 'Constant', size = 2.5) +\n  labs(x = 'Pair Label', y = 'Stimuli Magnitude') +\n  scale_x_continuous(breaks = 1:9) + \n  scale_y_continuous(limits = c(0, 100)) +\n  theme(panel.grid.major.x = element_blank(),\n        panel.grid.minor.x = element_blank(),\n        aspect.ratio = 1/2,\n        panel.grid.major.y = element_line(color = 'grey70'),\n        panel.grid.minor.y = element_line(color = 'grey80', linetype = 'dashed'))\n```\n\n::: {.cell-output-display}\n![Values for stimuli in the heatmap experiment. All values are paired with the constant stimuli of 50 units, creating nine pairs of stimuli.](index_files/figure-pdf/fig-stimuli-values-1.pdf){#fig-stimuli-values fig-pos='H' fig-scap='Stimuli values paired with a fixed reference'}\n:::\n:::\n\n\n\n\nTwo datasets were created for the experiment. To generate non-stimuli random values, we used a mixture distribution of random uniform noise and a mathematical function to populate our coordinate grid. The mathematical functions are scaled between 0 and 100, $g(Z)=100\\cdot\\frac{Z-\\min(Z)}{\\max(Z)-min(Z)}$. The first dataset, set 1, used the formula for the top half of a sphere that is centered within our X and Y coordinate grid, $f_1(X,Y)=\\sqrt{7^2-(X-\\bar{X})^2-(Y-\\bar{Y})^2}$, where $\\bar{X}$ and $\\bar{Y}$ are the averages of the $X$ and $Y$ coordinate ranges. The second dataset is calculated similarly using the formula for the bottom half of a sphere, $f_2(X,Y)=\\sqrt{7^2-(X-\\bar{X})^2+(Y-\\bar{Y})^2}$. Denoting $Z$ as the random values, $U(0,100)$ as a random variable drawn from a continuous uniform distribution between 0 and 100, and $X,Y$ as heatmap coordinates, our random heatmap data is calculated in @eq-random-z with $c=0.3$. An example of varying $c$ values is presented in @fig-random-z.\n\n$$\nZ=c\\cdot U(0,100)+(1-c)\\cdot g(f_i(X,Y))\n$$ {#eq-random-z}\n\n::: {#fig-random-z layout-ncol=\"5\" fig-scap=\"Randomization parameter effects on heatmap structure\"}\n![$c=0$](plots/z100.png){#fig-z100 fig-scap='Randomization parameter c equals 0'}\n\n![$c=0.25$](plots/z75.png){#fig-z75 fig-scap='Randomization parameter c equals 0.25'}\n\n![$c=0.5$](plots/z50.png){#fig-z50 fig-scap='Randomization parameter c equals 0.5'}\n\n![$c=0.75$](plots/z25.png){#fig-z25 fig-scap='Randomization parameter c equals 0.75'}\n\n![$c=1$](plots/z0.png){#fig-z0 fig-scap='Randomization parameter c equals 1'}\n\nMixture distribution of @eq-random-z using the formula for the top half of a sphere. As $c$ approaches 1, the distribution resembles uniform random noise.\n:::\n\nThe placement of stimuli values onto the randomly generated heatmap data was done via simulation to try to make their placement look as natural as possible. Twenty random heatmaps were generated. For each heatmap, the non-constant stimuli was placed onto the coordinate such that the difference between the stimuli and randomly generated value is minimized. The constant stimuli was then placed onto a coordinate within a Manhattan distance of three or four that minimizes the difference between the constant stimuli and randomly generated values, where the Manhattan distance is given by $|X_i - X_j| + |Y_i - Y_j|$ for stimuli $i$ and $j$. To ensure that stimuli placement is evenly positioned across the heatmap, the count of stimuli was computed separately across the X and Y axes. For example, in Data Set 1, the X-axis has four stimuli in $X=1$, three stimuli in $X=2$, and so forth. Chi-squared statistics were calculated for each axis and the heatmap with the smallest average Chi-squared statistic was selected as the final dataset. A visual inspection of this process showed that the stimuli were not clustered in any one area of the chart and that the stimuli look natural with respect to the random mixture distribution.\n\n\n\n\n::: {#fig-placement .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nload('../../data/data1.rda')\nload('../../data/data2.rda')\ndata1 %>% \n  ggplot(mapping = aes(x = x, y = y, fill = !is.na(pair_id))) + \n  geom_tile(color = 'black') + \n  geom_text(aes(label = pair_id)) + \n  scale_fill_manual(values = c('FALSE'='white', 'TRUE'='#1a80bb')) + \n  scale_x_continuous(breaks = 1:10) + \n  scale_y_continuous(breaks = 1:10) + \n  labs(x = 'Factor 1', y = 'Factor 2') + \n  theme_minimal() + \n  theme(aspect.ratio = 1, legend.position = 'none', panel.grid = element_blank()) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 82 rows containing missing values or values outside the scale range\n(`geom_text()`).\n```\n\n\n:::\n\n```{.r .cell-code}\ndata2 %>% \n  ggplot(mapping = aes(x = x, y = y, fill = !is.na(pair_id))) + \n  geom_tile(color = 'black') + \n  geom_text(aes(label = pair_id)) + \n  scale_fill_manual(values = c('FALSE'='white', 'TRUE'='#1a80bb')) + \n  scale_x_continuous(breaks = 1:10) + \n  scale_y_continuous(breaks = 1:10) + \n  labs(x = 'Factor 1', y = 'Factor 2') + \n  theme_minimal() + \n  theme(aspect.ratio = 1, legend.position = 'none', panel.grid = element_blank()) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 82 rows containing missing values or values outside the scale range\n(`geom_text()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Placement of stimuli on Set 1](index_files/figure-pdf/fig-placement-1.pdf){#fig-placement-1 fig-scap='Stimuli placement across two data sets' width=95%}\n:::\n\n::: {.cell-output-display}\n![Placement of stimuli on Set 2](index_files/figure-pdf/fig-placement-2.pdf){#fig-placement-2 fig-scap='Stimuli placement across two data sets' width=95%}\n:::\n\nPlacement of stimuli on the two data sets. Tiles with solid fills are the fixed stimuli values, where white tiles are randomly generated.\n:::\n\n\n\n\n### Charts\n\nThree types of charts were considered for this study: digital and static 2D (2dd), digital and interactive 3D (3dd), and 3D-printed (3dp). We constructed these charts so that they were as similar as possible, but inherent differences in dimensionality led to artistic decisions that attempt to focus solely on the dimensionality of the charts. The process of creating the charts is discussed in this section.\n\nThe 3D-printed charts were rendered with OpenSCAD [@kintelOpenSCADDocumentation2023]. To include plot text, a 120mm by 120mm by 10mm base was created with a solid color that was either white or black. Cells of the heatmap measured 10mm by 10mm, resulting in a heatmap that is 100mm by 100mm and is centered on the base. The upper bound of the height of heatmap values is 100mm, where 1-unit in the heatmap data is represented by 1mm of height on the heatmap. Once rendered, the heatmap was saved to 3D Manufacturing Format (3mf) and Standard Triangle Language (stl) files. A variety of solid and gradient filaments were tested for the bars of the 3D prints, and we eventually settled on a rainbow gradient. Some charts were printed with a white base and black text, and other charts had a black base with white text. An example of the 3D-printed chart is shown in @fig-3dp.\n\n::: {#fig-3dp layout-ncol=\"2\" fig-cap=\"3D printed heatmaps.\" fig-scap=\"3D-printed heatmaps for both data sets\"}\n![Data Set 1](images/3dp-gradient-set1.JPG){#fig-3dp-gradient fig-scap='3D-printed heatmap for data set 1'}\n\n![Data Set 2](images/3dp-gradient-set2.JPG){#fig-3dp-solid fig-scap='3D-printed heatmap for data set 2'}\n:::\n\nTo closely match the 3D-digital chart to the 3D-printed chart, multiple stl files were created for each colored component and combined with the RGL package [@rgl]. The base was rendered with white smoke (#F5F5F5) to slightly contrast with the default white background color (#FFFFFF). Heatmap tiles were rendered with cyan (#74CCFF) and text labels were rendered with black (#000000). Lighting was fixed at 45 degree angles at two opposite corners of the chart. The end result was a near-perfect replica of the 3D-printed charts, with the exception of different heatmap tile colors [@fig-3dd].\n\n![RGL rendering of Data Set 2 for 3dd charts.](images/chart-3dd.png){#fig-3dd fig-height=\"3in\" fig-scap='Interactive 3D digital rendering'}\n\nUnlike the 3D charts, the 2D charts needed a different encoding to convey heatmap values. The 2D heatmaps were created with `ggplot2` [@ggplot2] using `geom_tile()`. Fill colors for the cells use a color gradient ranging from Blue Zodiac (#0C2841) to Malibu (#66D9FF), which were selected from a color picker using shadows on our initial 3D-printed charts. The color interpolation was performed with the `scale_fill_gradient()` function from the `ggplot2` package.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mapping = aes(x = 1:10, y = 0)) + \n  geom_tile(color = NA, fill = colorRampPalette(c('#0C2841','#66D9FF'))(10)) + \n  theme_void() + \n  coord_equal()\n```\n\n::: {.cell-output-display}\n![Color palette for 2D-digital charts. The colors are interpolated from #0C2841 to #66D9FF, which are the colors of the lighting conditions for a 3D-printed chart created with cyan filament.](index_files/figure-pdf/fig-color-pal-1.pdf){#fig-color-pal fig-pos='H' fig-scap='Color palette for 2D digital heatmaps'}\n:::\n:::\n\n\n\n\n### Subject Recruitment\n\nParticipants were recruited from STAT 218: *Introduction to Statistics* at the University of Nebraska-Lincoln in the summer and fall of 2025. The experiment was incorporated into the curriculum as a project that allowed students to get hands-on experience with statistics. For data to be collected as part of our study, students had to be at least 19 years old (age of majority in Nebraska) and consent to participation.\n\nSTAT 218 is a general education statistics course at the University of Nebraska. As such, many students enrolled in the course are in the 18-25 age range and are in the process of obtaining a Bachelor's degree. This allowed for the unique opportunity for us to obtain a sample size that is larger than typical studies in graphical perception, and that could accommodate in-person participation required for the 3D printed charts. Some sections of STAT 218 were held online in an asynchronous format.\n\n### Experimental Design\n\nOur experiment was designed with a 3 media type x 2 datasest x 9 comparison treatment structure. Media type is our main interest, with 2D-digital, 3D-digital, and 3D-printed charts. To ensure that results are not confounded with datasets, we used two datasets, with a total of 9 stimuli pairs in each dataset. The order of treatments was given so that media and dataset combinations were grouped together randomly in the sequence with stimuli pairs randomized within the groupings. This meant participants did not have to switch charts as frequently, reducing the risk of using the wrong chart. For students enrolled in online sections of STAT 218, the 3D-printed charts were removed from their trials as they were not required to be on campus.\n\nDue to practical constraints, stimuli pairs were incompletely blocked. A full factorial design would result in 54 trials per participant, which could lead to a decrease in quality responses [@herzog1981]. Therefore, we selected four out of the nine possible stimuli pairs to create incomplete blocks for each chart. This resulted in 18 blocks for a balanced incomplete block design. Within each block, media type is fully crossed with dataset. Using the incomplete block structure, participants completed a total of 24 trials, which is more practical than the full factorial design.\n\nFollowing the procedure of @cleveland1984, we asked participants two questions in each trial. The first question asked participants which stimuli in a specified pair is larger or if the stimuli are the same value. Next, participants were asked to estimate the magnitude of the smaller stimuli if the larger stimuli represents 100 units, which is a subtractive process [@veit]. This question is designed to estimate $A/B$, where $A\\leq B$.\n\n#### Shiny Application\n\nA Shiny application [@shiny] was developed to administer the experiment. The application consisted of five sections: informed consent, demographics, practice, experiment, and wrap-up. The entire application was designed to be completed in approximately 30 minutes.\n\nThe Shiny application started with the informed consent screen, allowing participants to select if they are a STAT 218 Student and if they agree to the data collection. Participants had to select a data collection option to continue. After submitting their data collection response, a completion code was generated and saved on the last page of the application. This code was required for class, but participant consent was only required to save the data, so underage participants could still get the code for course credit.\n\nIf participants agreed to have their data collected, they were presented with the demographics section. This section asked participants about their age, gender identity, highest education level, and how their participation in the experiment is graded. The last question was a text box and asked participants to specify their favorite movie and/or actor. Demographic information was combined with the application start time and completion code to create a hash for an anonymized participant identifier using the `rlang` package [@rlang].\n\nOnce a participant completed the demographics page or selected \"No\" to the data collection question, they were given a practice page. A modal dialog window was initially shown with instructions, and users could display this window again at any point during the practice trials. The practice consisted of four questions: two trials from 2dd charts and two trials from 3dd charts. Once participants provided a response to both questions in a practice trial, they were able to display the correct solution to check their answers. Since the practice trials were only to inform participants about the mechanics for answering the questions, we did not include 3D-printed charts. This eliminated the possibility of participants using a practice chart for the experiment.\n\nThe experiment page was presented to participants after completion of the practice trials [@fig-exp-page]. Each page contained two questions -- one question for identifying which stimuli is larger and another question for estimating the value of the smaller stimuli if the larger stimuli is 100 units. Each trial had the initial slider position randomized in order to prevent starting position bias. For 3dd charts, the number of interactive clicks was also recorded. A trial could only be submitted if the first question is answered and if the slider was moved at least once.\n\n![Graphics experiment page. Each trial contained two questions about a pair of stimuli, and a check box that displays the location of the stimuli if needed.](images/experiment-page.png){#fig-exp-page width=\"100%\" fig-scap='Experiment interface for pairwise responses'}\n\nAfter completing all trials, participants were given the completion code and informed to provide the code to their instructor since they would not have access to the code after closing out of the experiment.\n\n#### Method of Analysis\n\nThe design of our experiment is a balanced incomplete split-plot with replication, where media type and dataset are whole-plot factors for each participant and stimuli pair is the split plot. A similar design was presented by @mandal2020 for a single replicate. For our analysis, we used the following model as a baseline:\n\n$$\nY_{ijklm}=\\mu+S_i\\times M_j\\times P_k+\\gamma_{lm}+\\omega_{ijlm}+\\epsilon_{ijklm}\n$$\n\nIn our model, $Y_{ijklm}$ is a metric of error for participant responses to the ratio estimation question, $S_i$ is the effect of dataset $i$, $M_j$ is the effect of chart type $j$, $P_k$ is the effect of stimuli pair $k$, and $S_i\\times M_j\\times P_k$ includes all corresponding main effects and two-way and three-way interactions. Our random effects include $\\gamma_{lm}\\sim N(0,\\sigma^2_A)$ for participant $m$ in block $l$, $\\omega_{ijlm}\\sim N(0,\\sigma^2_B)$ for the ordering of dataset $i$ and chart type $j$ for participant $m$ in block $l$, and $\\epsilon_{ijklm}\\sim N(0, \\sigma^2_C)$ for the residual error. We assume that $\\gamma_{lm}$, $\\omega_{ijlm}$, and $\\epsilon_{ijklm}$ are independently and identically distributed.\n\nThe first question in each trial was to indicate which value within a stimulus pair was larger, or if they were the same value. Following @cleveland1984, we use this question as an attention check to verify that participants are following the procedure and that the correct comparison is being made.\n\n## Results\n\nIn this section, we describe the demographic information of our sample, cleaning of participant responses, analysis of responses, and interactions participants had with the Shiny application.\n\n### Demographics\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine users and results, remove all \"test\" entries\nusers_clean <- results %>% \n  inner_join(users, by = 'user_id', relationship = 'many-to-many') %>% \n  select(user_id, user_age:user_unique) %>% \n  distinct() %>% \n  dplyr::filter(!str_detect(tolower(user_unique), 'test,'))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get in-person users (have at least 1 3dp trial)\nusers_in_person <- users_clean %>% \n  inner_join(results) %>% \n  group_by(user_id, media) %>% \n  summarise(n = n()) %>% \n  filter(media == '3dp' & n > 0) %>% \n  select(user_id)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(user_id)`\n`summarise()` has regrouped the output.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nres_q1 <- results %>% \n  inner_join(users_clean, by = 'user_id') %>% \n  mutate(q1 = case_when(\n    user_larger == 'Both values are the same' ~ 'Equal',\n    (user_larger != true_larger) & (user_larger != 'Both values are the same') ~ 'Smaller',\n    user_larger != 'Both values are the same' & user_larger == true_larger ~ 'Larger'\n  ), correct_label = ifelse(user_larger == true_larger, '*', NA)) %>%\n  mutate(q1_label = factor(q1, labels = c('Smaller value\\n(or incorrect)', \n                                          'Equal', 'Larger value'), \n                           levels = c('Smaller', 'Equal', 'Larger'), ordered = T),\n         prop = round(100*true_ratio,1),\n         facet_label = paste0('Stimuli Pair ', pair_id, ' (', prop, '%)'),\n         q1 = factor(q1, levels = c('Smaller', 'Equal', 'Larger'), ordered = F))\n\nres_q1_filtered <- res_q1 %>% \n  filter(pair_id != 5) %>% \n  group_by(user_id) %>% \n  summarize(n_trials = n(),\n            n_correct = sum(user_larger == true_larger),\n            p.value = pbinom(n_correct, size = n_trials, prob = 2/3, lower.tail = F)) %>% \n  ungroup() %>% \n  filter(p.value <= 0.05)\n\nres_q2 <- results %>%\n  mutate(q2_error = user_slider - target_ratio,\n         q2_error_cm = log2(abs(user_slider - target_ratio) + 1/8))\nres_q2_filtered <- res_q2 %>% inner_join(res_q1_filtered)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(user_id)`\n```\n\n\n:::\n:::\n\n\n\n\nOur experiment was conducted with eight sections of Stat 218 between August 25th and December 19th in 2025 at the University of Nebraska. To participate in the experiment, students were instructed to visit communal office hour locations to access the 3D printed charts. We recorded 482 interactions with the shiny application, of which 259 students completed the entirety of the experiment. Of these students, 92 were enrolled in online sections of the course and did not have access to the 3D printed charts. The vast majority of participants were actively completing their undergraduate degree and between the ages of 19 and 25. Full demographic information can be found in @tbl-demographics.\n\n\n\n\n::: {#tbl-demographics .cell tbl-cap='Demographic Information'}\n\n```{.r .cell-code}\ntbl_gender <- users_clean %>% \n  group_by(user_gender) %>% \n  summarize(n = n()) %>% \n  ungroup() %>% \n  mutate(prop = n/sum(n)) %>% \n  mutate(user = user_gender)\n\ntbl_age <- users_clean %>% \n  group_by(user_age) %>% \n  summarize(n = n()) %>% \n  ungroup() %>% \n  mutate(prop = n/sum(n)) %>% \n  mutate(user = user_age)\n\ntbl_education <- users_clean %>% \n  group_by(user_education) %>% \n  summarize(n = n()) %>% \n  ungroup() %>% \n  mutate(prop = n/sum(n)) %>% \n  mutate(user = user_education)\n\ntbl_demographics <- bind_rows(tbl_gender, tbl_age, tbl_education) %>% \n  select(-c(user_gender, user_age, user_education)) %>% \n  bind_rows(data.frame(\n    user = '31-35',\n    n = 0,\n    prop = 0\n  ))\n  \ntbl_demographics[c(1,2,4,3, 5, 6, 16, 7, 8, 9, 11, 14, 15, 13, 10, 12), c(3,1,2)] %>% \nkbl(digits = 2, booktabs = T, col.names = c('', 'Count', 'Proportion')) %>% \n  kable_paper() %>% \n  pack_rows('Gender', 1, 4) %>% \n  pack_rows('Age', 5, 10) %>% \n  pack_rows('Education', 11, 16)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{lrr}\n\\toprule\n & Count & Proportion\\\\\n\\midrule\n\\addlinespace[0.3em]\n\\multicolumn{3}{l}{\\textbf{Gender}}\\\\\n\\hspace{1em}Female & 166 & 0.64\\\\\n\\hspace{1em}Male & 90 & 0.35\\\\\n\\hspace{1em}Variant/Nonconforming & 1 & 0.00\\\\\n\\hspace{1em}Prefer not to answer & 2 & 0.01\\\\\n\\addlinespace[0.3em]\n\\multicolumn{3}{l}{\\textbf{Age}}\\\\\n\\hspace{1em}19-25 & 252 & 0.97\\\\\n\\hspace{1em}26-30 & 2 & 0.01\\\\\n\\hspace{1em}31-35 & 0 & 0.00\\\\\n\\hspace{1em}36-40 & 1 & 0.00\\\\\n\\hspace{1em}41-45 & 3 & 0.01\\\\\n\\hspace{1em}Prefer not to answer & 1 & 0.00\\\\\n\\addlinespace[0.3em]\n\\multicolumn{3}{l}{\\textbf{Education}}\\\\\n\\hspace{1em}High School or Less & 23 & 0.09\\\\\n\\hspace{1em}Some Undergraduate Courses & 214 & 0.83\\\\\n\\hspace{1em}Undergraduate Degree & 12 & 0.05\\\\\n\\hspace{1em}Some Graduate Courses & 4 & 0.02\\\\\n\\hspace{1em}Graduate Degree & 2 & 0.01\\\\\n\\hspace{1em}Prefer not to answer & 4 & 0.02\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_time <- res_q2 %>% \n  group_by(user_id, block) %>% \n  summarise(total_time = (max(end_time)-min(start_time))/60)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has regrouped the output.\ni Summaries were computed grouped by user_id and block.\ni Output is grouped by user_id.\ni Use `summarise(.groups = \"drop_last\")` to silence this message.\ni Use `summarise(.by = c(user_id, block))` for per-operation grouping\n  (`?dplyr::dplyr_by`) instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian_time_in_person <- df_time %>% filter(user_id %in% users_in_person$user_id) %>% \n  pull(total_time) %>% \n  median()\n\nmedian_time_online <- df_time %>% filter(!(user_id %in% users_in_person$user_id)) %>% \n  pull(total_time) %>% \n  median()\n```\n:::\n\n\n\n\nAlmost all participants completed the experiment in under 20 minutes. Summary statistics can be found in @tbl-exp-times, with the overall distribution of times shown in @fig-total-time. Individual trials had a median completion time of 0.23 minutes.\n\n\n\n\n::: {#tbl-exp-times .cell}\n\n```{.r .cell-code}\ndf_time_grouped <- df_time %>% \n  mutate(Section = ifelse(user_id %in% users_in_person$user_id, 'In-person', 'Online')) %>% \n  group_by(Section) %>% \n  summarise(Mean = mean(total_time),\n            SD = sd(total_time),\n            Median = median(total_time))\ndf_time_total <- df_time %>% \n  mutate(Section = 'All Participants') %>% \n  group_by(Section) %>% \n  summarise(Mean = mean(total_time),\n            SD = sd(total_time),\n            Median = median(total_time))\n\nbind_rows(df_time_grouped, df_time_total) %>% \n  knitr::kable(digits = 2, caption = 'Summary of experiment completion times in minutes.')\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of experiment completion times in minutes.\n\n|Section          | Mean|   SD| Median|\n|:----------------|----:|----:|------:|\n|In-person        | 8.08| 3.39|   7.45|\n|Online           | 5.70| 3.42|   5.09|\n|All Participants | 7.23| 3.58|   6.86|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_time %>% \n  mutate(inperson = user_id %in% users_in_person$user_id) %>% \n  ggplot(mapping = aes(x = total_time, fill = inperson)) + \n  geom_histogram(binwidth = 1, boundary = 0, color = 'black') + \n  labs(x = 'Total time\\n(in minutes)', y = 'Count', fill = 'Section') + \n  scale_fill_manual(values = c('TRUE'='#1a80bb', 'FALSE' = '#b8b8b8'),\n                    labels = c('In-person','Online')) + \n  theme_bw() + \n  theme(aspect.ratio = 1/2)\n```\n\n::: {.cell-output-display}\n![Histogram of experiment completion times. Online participants had generally shorter completion times due to a decreased number of trials.](index_files/figure-pdf/fig-total-time-1.pdf){#fig-total-time fig-pos='H' fig-scap='Distribution of participant completion times'}\n:::\n:::\n\n\n\n\nDuring our initial exploration of the results, we discovered a non-negligible number of students who did not follow the instructions, which is not surprising in an intro statistics class activity. In some cases, participants appeared to be using alternative estimation strategies, such as estimating the difference between the two values in a stimulus pair, rather than the specified ratio strategy. Additionally, we noticed that several students were randomly entering values in order to obtain the completion code at the end of the experiment. We provide some examples of individual participant responses in @fig-user-strategies to illustrate this issue.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# results %>% \n#   group_by(user_id) %>% \n#   summarize(corr_ratio = cor(user_slider, target_ratio)) %>% \n#   arrange(-corr_ratio)\n\nresults %>% \n  filter(user_id %in% c(\n    '773966d68f5e13e119b6d13c8f16a68e', #Ratio\n    '9fd7c7ca2fa26afd0b2ab532442a27c0', #Diff\n    '78ec9b96ed3ccdd7c796dd2010aebd5b'  #Random\n  )) %>% \n  mutate(strategy = case_when(\n    user_id == '773966d68f5e13e119b6d13c8f16a68e' ~ 'Ratio Strategy',\n    user_id == '9fd7c7ca2fa26afd0b2ab532442a27c0' ~ 'Difference Strategy(?)',\n    user_id == '78ec9b96ed3ccdd7c796dd2010aebd5b' ~ 'Random Strategy'\n  )) %>% \n  mutate(target = case_when(\n    user_id == '773966d68f5e13e119b6d13c8f16a68e' ~ target_ratio,\n    user_id == '9fd7c7ca2fa26afd0b2ab532442a27c0' ~ target_diff,\n    user_id == '78ec9b96ed3ccdd7c796dd2010aebd5b' ~ 50\n  )) %>% \n  ggplot(mapping = aes(x = user_trial_order, y = user_slider, group = user_id)) + \n  geom_col(aes(y = 100, fill = media), alpha = 1/5, color = NA, width = 1) + \n  geom_line(aes(linetype = 'user'), alpha = 1) + facet_wrap(~strategy, scales = 'free_x', nrow = 2) + \n  geom_point(aes(shape = user_larger == true_larger)) + \n  scale_x_continuous(breaks = seq(1,24, by = 4)) +\n  geom_line(aes(y = target, linetype = 'suspect'), alpha = 2/3) +\n  geom_line(aes(y = target_ratio, linetype = 'target'), alpha = 2/3) +\n  scale_linetype_manual(labels = c('User response', 'True target', 'Suspected target'),\n                        values = c('user'='solid','suspect'='dotted','target'='dashed'),\n                        breaks = c('user', 'target', 'suspect')) +\n  scale_shape_manual(values = c('TRUE' = 16, 'FALSE' = 4), labels = c('Incorrect', 'Correct')) +\n  labs(x = 'Trial Number', y = 'Slider Position\\n(0 - 100)',\n       fill = 'Chart Type', linetype = 'Strategy', shape = 'Larger value\\nidentified correctly') + \n  theme_bw() + \n  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())\n```\n\n::: {.cell-output-display}\n![Three potential estimation strategies from participants. Many participants followed instructions to estimate ratios. However, some participants appeared to estimate the difference between stimuli pairs or submitted random values.](index_files/figure-pdf/fig-user-strategies-1.pdf){#fig-user-strategies fig-pos='H' fig-scap='Examples of participant estimation strategies'}\n:::\n:::\n\n\n\n\nIt is commonly acknowledged in psychology that careless respondents should be addressed to some degree, although there is no general consensus on how to handle this without cherry picking [@jasoIdentificationCarelessResponding2021; @ward2023]. Some proposed solutions include removing participants based on observed patterns or fitting mixture models to address latent class variables. In this section, we discuss one possible subset of participant responses to address careless respondents. We also include several alternative models in the appendix.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_q1 <- results %>% \n  inner_join(users_clean, by = 'user_id') %>% \n  mutate(q1 = case_when(\n    user_larger == 'Both values are the same' ~ 'Equal',\n    (user_larger != true_larger) & (user_larger != 'Both values are the same') ~ 'Smaller',\n    user_larger != 'Both values are the same' & user_larger == true_larger ~ 'Larger'\n  ), correct_label = ifelse(user_larger == true_larger, '*', NA)) %>%\n  mutate(q1_label = factor(q1, labels = c('Smaller value\\n(or incorrect)', \n                                          'Equal', 'Larger value'), \n                           levels = c('Smaller', 'Equal', 'Larger'), ordered = T),\n         prop = round(100*true_ratio,1),\n         facet_label = paste0('Stimuli Pair ', pair_id, ' (', prop, '%)'),\n         q1 = factor(q1, levels = c('Smaller', 'Equal', 'Larger'), ordered = F))\n\nres_q1_filtered <- res_q1 %>% \n  filter(pair_id != 5) %>% \n  group_by(user_id) %>% \n  summarize(n_trials = n(),\n            n_correct = sum(user_larger == true_larger),\n            p.value = pbinom(n_correct, size = n_trials, prob = 2/3, lower.tail = F)) %>% \n  ungroup() %>% \n  filter(p.value <= 0.05)\n```\n:::\n\n\n\n\n### Addressing Random Categorical Responses {#sec-remove-random-categories}\n\nTo improve the quality of our data, we started by assessing random guesses in identifying the larger value of a stimulus pair. In each trial, participants have a 1 out of 3 chance for correctly identifying the larger value if they are randomly guessing. Since stimuli pair 5 contains identical values, we temporarily exclude those trials to focus on stimuli pairs where there was a difference between the values. For each participant, we test $H_0: \\pi\\leq2/3\\text{ vs. }H_1:\\pi>2/3$ with $\\alpha=0.05$, where $\\pi$ is the probability of a participant correctly answering the initial question and $\\alpha$ is the level of the test. That is, participants who are following instructions should select the correct option at least twice as often as either incorrect alternative. Given the lack of standardized criteria for identifying careless responding, the one-sided Binomial test should extract users who are suspected to be following the instructions. Using the first question for participant screening, 98 participants are excluded for suspected random selecting, leaving 161 participants. The effect of this exclusion can be seen in @fig-q1-eda.\n\n\n\n\n::: {#fig-q1-eda .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nres_q1 %>% \n  ggplot(mapping = aes(y = media, fill = q1_label)) + \n  geom_bar(position = position_fill()) + \n  labs(x = 'Proportion', y = 'Media type', fill = 'Participant Selection') + \n  facet_wrap(~facet_label) + \n  scale_fill_manual(values = c(\n    'Larger value' = '#2066a8',\n    'Equal' = '#3594cc',\n    'Smaller value\\n(or incorrect)' = '#8cc5e3'\n  )) + \n  theme_bw() + \n  theme(aspect.ratio = 1/3,\n        panel.grid = element_blank(),\n        legend.position = 'bottom')\n\nres_q1 %>% \n  inner_join(res_q1_filtered) %>% \n  ggplot(mapping = aes(y = media, fill = q1_label)) + \n  geom_bar(position = position_fill()) + \n  labs(x = 'Proportion', y = 'Media type', fill = 'Participant Selection') + \n  facet_wrap(~facet_label) + \n  scale_fill_manual(values = c(\n    'Larger value' = '#2066a8',\n    'Equal' = '#3594cc',\n    'Smaller value\\n(or incorrect)' = '#8cc5e3'\n  )) + \n  theme_bw() + \n  theme(aspect.ratio = 1/3,\n        panel.grid = element_blank(),\n        legend.position = 'bottom')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(user_id)`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![No participant filtering](index_files/figure-pdf/fig-q1-eda-1.pdf){#fig-q1-eda-1 fig-scap='Question 1 accuracy by stimuli pair and media' width=90%}\n:::\n\n::: {.cell-output-display}\n![Exclude random guessers](index_files/figure-pdf/fig-q1-eda-2.pdf){#fig-q1-eda-2 fig-scap='Question 1 accuracy by stimuli pair and media' width=90%}\n:::\n\nProportion of correct responses to Question 1 across stimuli pairs and media types. For all pairs, with the exception of Pair 5, a correct answer was 'Larger value'. Stimuli Pair 5 had two identical values, meaning that options other than 'Both values are the same' were incorrect.\n:::\n\n\n\n\n### Analysis of Error\n\nWe follow the same calculation of error as @cleveland1984, which is shown in @eq-error_cm. Error is defined as the base-2 logarithm of the absolute estimation error meaning that differences of one unit on this scale correspond to approximately doubling the size of the error. The addition of 1/8 prevents distortion for responses with near-zero error.\n\n$$\ny=\\log_2(|\\text{User Response}-100\\times(\\text{True ratio})|+1/8)\n$$ {#eq-error_cm}\n\nIn our analysis, we excluded individual responses where participants were incorrect in their response to the initial question and all responses for stimuli pair 5. The initial question served as an attention check to verify that the participants were making the correct comparison between stimuli values. For stimuli pair 5, we removed these trials since correct solutions should be a binary response. However, we discovered a discrepancy in how participants were responding to both questions for these trials, which we discuss in the appendix.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_q2 <- lmer(q2_error_cm ~ set*media*pair_id + (1|user_id:block/set:media),\n               data = filter(res_q2_filtered, pair_id != 5 & user_larger==true_larger))\nmod_q2_anova <- car::Anova(mod_q2, type = 3, test = 'F')\np.vals_mod2 <- mod_q2_anova$`Pr(>F)`\n```\n:::\n\n\n\n\nWith our specified exclusion criteria, we find that there was marginal evidence for the effects of chart type (p-value = 0.041) and the data set and stimuli pair interaction (p-value = 0.073). This finding is consistent with models fitted with various participant and response filters.\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n:::\n\n\n\n\nOur findings suggest that the 2D heatmaps had evidence of higher log absolute error than either type of the 3D heatmaps. On the base-2 log scale, the error for 2D heatmaps was larger than the error for digital 3D heatmap by 0.414 (95% CI: 0.253, 0.574). This finding is similar for the 3D printed heatmaps, where the log absolute error for 2D heatmaps was larger by 0.413 (95% CI: 0.234, 0.591). There were no detectable differences in error between the digital and physical 3D heatmaps (p-value = 1).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggsignif)\nres_q2_filtered %>% \n  ggplot(mapping = aes(x = media)) + \n  geom_violin(aes(y = q2_error_cm), fill = '#2066a8') + \n  geom_point(aes(y = emmean),\n           data = data.frame(em), size = 1) + \n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL),\n                data = data.frame(em), width = 1/10) + \n  geom_signif(\n    aes(y = emmean),\n    data = data.frame(em),\n    comparisons = list(c('2dd', '3dd'), c('2dd', '3dp')),\n    margin_top = 0.1,\n    step_increase = 0.1,\n    tip_length = 0.05,\n    map_signif_level = function(p) '***'\n  ) + \n  labs(x = 'Chart Type', y = 'log2(|Error|+1/8') + \n  scale_y_continuous(limits = c(-3.2, 9.5), breaks = seq(-5, 15, by = 2.5)) +\n  theme_bw() + \n  theme(aspect.ratio = 1/2, panel.grid.major.x = element_blank())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_signif(aes(y = emmean), data = data.frame(em), comparisons =\nlist(c(\"2dd\", : You have set data and mapping, are you sure that manual = FALSE\nis correct?\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Distributions of log error overlayed with estimated marginal means and their 95% confidence intervals. Differences were only detected between 2D heatmap and both types of 3D heatmaps, where the 2D heatmap had evidence of larger errors.](index_files/figure-pdf/fig-em-media-1.pdf){#fig-em-media fig-pos='H' fig-scap='Marginal means of log error by media type'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nem2 <- emmeans(mod_q2, ~pair_id + set)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n```{.r .cell-code}\n# em2\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(em2) %>% \n  data.frame() %>% \n  separate(contrast, into = c('p1','p2'), sep = ' - ') %>% \n  pivot_longer(cols = c(p1, p2)) %>% \n  filter(p.value <= 0.05) %>% \n  group_by(value) %>% \n  count() %>% \n  arrange(-n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npairs2 <- pairs(em2) %>% \n  data.frame() %>% \n  filter(p.value < 0.05) %>% \n  arrange(p.value)\n```\n:::\n\n\n\n\nWhen examining the interaction between stimuli pairs and underlying datasets, 11 differences in log absolute error were detected at the $\\alpha=0.05$ level. Seven of these differences occurred with stimuli pair 6 (ratio = 0.889) and dataset 1, which had the smallest estimated marginal mean of log absolute error. All differences can be found in @fig-em-set-pair, where significant differences are assessed via a compact letter display from the `multcomp` package [@multcomp].\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmultcomp::cld(em2, Letters = letters) %>% \n  data.frame() %>% \n  left_join(mutate(solutions, pair_id = as.factor(pair_id))) %>% \n  mutate(label = paste0('Pair ', pair_id, '\\n(', round(100*true_ratio, 1), '%)')) %>% \n  ggplot(mapping = aes(x = reorder(label, true_ratio), y = emmean)) + \n  labs(x = '', y = 'Estimated Marginal Mean\\nlog2(|Error| + 1/8)', fill = 'Dataset') +\n  geom_col(aes(fill = set), position = position_dodge(), width = 2/3) + \n  geom_text(aes(label = trimws(.group), y = 0.2, color = set), position = position_dodge(2/3),\n            angle = 0,\n            hjust = 0.5,\n            size = 2) +\n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL, color = set),\n                position = position_dodge(2/3), width = 1/4) +\n  scale_color_manual(values = c('set1' = 'black', 'set2' = 'black')) +\n  scale_fill_manual(values = c('set1' = '#1a80bb', 'set2'='#8cc5e3')) + \n  guides(color = 'none') +\n  theme_bw() + \n  theme(aspect.ratio = 1/2, panel.grid.major.x = element_blank())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(pair_id, set)`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Estimated marginal means of stimuli pair and dataset. Bars sharing the same letter are not significantly different from one another.](index_files/figure-pdf/fig-em-set-pair-1.pdf){#fig-em-set-pair fig-pos='H' fig-scap='Marginal means by stimuli pair and data set'}\n:::\n:::\n\n````{=html}\n<!--- Honestly not sure if I want to include this section. While it would be nice to have a similar result to CM, the design of the experiment was different.\n\n### A 1980s bootstrap\n\nIn addition to our contemporary mixed effects model, we present results following the bootstrap procedure as described by @cleveland1984. To account for the complex correlation between judgements, 1,000 bootstrap samples of size 161 were drawn from the sample of 161 participants with replacement. In each sample, midmeans were computed for each combination of chart type, dataset, and stimuli pair. Means and confidence intervals of the bootstrap sampling are presented in @fig-bootstrap-95, where 95% confidence intervals are calculated as the mean of midmeans plus and minus 1.96 times the standard deviation of the midmeans. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(213)\nbootstrap <- data.frame()\nfor(i in 1:1000) {\n  one_sample <- res_q2_filtered %>% \n    filter(user_larger==true_larger & pair_id != 5) %>% \n    group_by(user_id, block) %>% \n    nest() %>% \n    ungroup() %>% \n    slice_sample(prop = 1, replace = T) %>% \n    arrange(user_id) %>% \n    unnest(data) %>% \n    group_by(media, pair_id, set) %>% \n    summarize(midmean = mean(q2_error_cm, trim = 0.25), .groups = 'keep') %>% \n    mutate(sample = i)\n  bootstrap <- bind_rows(bootstrap, one_sample)\n}\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap %>% \n  group_by(media, pair_id, set) %>% \n  summarize(mean = mean(midmean),\n            sd = sd(midmean)) %>% \n  ggplot(mapping = aes(y = media, x = mean)) + \n  geom_point(size = 0.5) + \n  geom_errorbar(aes(xmin = mean-1.96*sd, xmax = mean+1.96*sd), width = 1/4) + \n  labs(x = 'Log2 (Absolute Error + 1/8)', y = 'Chart type') + \n  facet_grid(set ~ pair_id, labeller = label_both) + \n  scale_x_continuous(breaks = seq(0,10, by = 1)) + \n  theme_bw() +\n  theme(aspect.ratio = 1, \n        axis.text.x = element_text(size = 6),\n        panel.grid.major.x = element_blank(),\n        panel.grid.minor.x = element_blank())\n```\n:::\n\nThe procedure for calculating 95% confidence intervals for pairwise differences is defined as follows. .... **FINISH THIS SECTION**\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_midmeans_wide <- bootstrap %>%\n  mutate(trt = paste(media, pair_id, set, sep = '_')) %>% \n  select(sample, trt, midmean) %>% \n  pivot_wider(names_from = trt, values_from = midmean)\n\nmat_midmeans <- as.matrix(df_midmeans_wide[,-1])\nmat_means <- colMeans(mat_midmeans)\ntrt_names <- colnames(mat_midmeans)\n\nall_combs <- combn(trt_names, 2)\n\npairwise <- data.frame()\n\nfor(i in 1:ncol(all_combs)) {\n  tmp_diff_trts <- all_combs[,i]\n  tmp_mean_diffs <- as.numeric(mat_means[tmp_diff_trts[1]] - \n                                 mat_means[tmp_diff_trts[2]])\n  tmp_all_diffs <- as.numeric(mat_midmeans[,tmp_diff_trts[1]] - \n                                 mat_midmeans[,tmp_diff_trts[2]])\n  sd_ij <- sd(tmp_all_diffs)\n  \n  lhs <- abs(tmp_mean_diffs - tmp_all_diffs)\n  tmp_df <- data.frame(\n    contrast = paste(tmp_diff_trts, collapse = ' - '),\n    lhs = lhs,\n    sd_ij = sd_ij\n  )\n  \n  pairwise <- bind_rows(pairwise, tmp_df)\n  \n}\n\n# Find c\npairwise %>% \n  summarize(mean(lhs <= sd_ij))\n\nc_many <- seq(1.929293, 2.090909, l = 100)\n\nexpand_grid(pairwise, c_many) %>% \n  group_by(c_many) %>% \n  summarise(prop_true = mean(lhs<=c_many*sd_ij)) %>% \n  mutate(c_many = round(c_many, 2))\n```\n:::\n\n\nThe value for $c$ such that 95% of pairwise differences was computed to be 1.96. \n\n\n\n--->\n````\n\n\n\n\n### Participant Interactions with Shiny Application\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime <- res_q2_filtered %>% \n  ungroup() %>% \n  mutate(ttc = end_time - start_time)\nclicks <- res_q2_filtered %>% \n  filter(media == '3dd')\n\nover_60 <- time %>% \n  filter(ttc >=60) %>% \n  group_by(user_id, block) %>% \n  count() %>% \n  arrange(-n)\n```\n:::\n\n\n\n\nIn this section, we describe participant interactions with the Shiny application using the same participant exclusion criteria as our model. As participants completed the experiment, we recorded the amount of time to complete each trial, the number of cursor clicks on the digital 3D heatmaps, and the number of times that the slider was moved. We also recorded the initial starting position of the slider, which was randomly placed for each trial.\n\nMany participants completed each trial in under 20 seconds. The median completion time was 14.8372396 seconds, with a standard deviation of 22.9971286 seconds. There were 91 participants who had at least one trial exceed 60 seconds. Due to the design and administration of the experiment, we are unable to account for the cause of longer trial completion times, but it is possible the students may have been interrupted or distracted before returning to the task.\n\n\n\n\n::: {#fig-time-summary .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ntime %>% \n  ggplot(mapping = aes(x = ttc, color = media)) + \n  geom_density() + \n  scale_x_continuous(limits = c(0, 60)) + \n  labs(x = 'Time spent per trial\\n(in seconds)',\n       color = 'Chart type') + \n  theme_bw() + \n  theme(aspect.ratio = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 137 rows containing non-finite outside the scale range\n(`stat_density()`).\n```\n\n\n:::\n\n```{.r .cell-code}\ntime %>% \n  ggplot(mapping = aes(x = ttc, y = q2_error_cm, color = media)) + \n  geom_point(alpha = 1/10) + \n  geom_smooth() +\n  scale_x_continuous(limits = c(0, 60)) + \n  labs(x = 'Time spent per trial\\n(in seconds)',\n       y = 'log2(|Error|+1/8)',\n       color = 'Chart type') + \n  theme_bw() + \n  theme(aspect.ratio = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 137 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 137 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Frequency plot](index_files/figure-pdf/fig-time-summary-1.pdf){#fig-time-summary-1 fig-scap='Trial-level time distribution and error relationship' width=90%}\n:::\n\n::: {.cell-output-display}\n![Time vs. Error](index_files/figure-pdf/fig-time-summary-2.pdf){#fig-time-summary-2 fig-scap='Trial-level time distribution and error relationship' width=90%}\n:::\n\nVisual summary of time spent on each trial. 137 trials are omitted due to lasting longer than 60 seconds.\n:::\n\n::: {#fig-clicks3dd .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nclicks %>% \n  ggplot(mapping = aes(x = clicks_3dd)) + \n  geom_histogram(binwidth = 1, color = 'black', fill = '#1a80bb',\n                 boundary = 0) + \n  theme_bw() + \n  theme(aspect.ratio = 1) + \n  labs(x = 'Number of WebGL clicks',\n       y = 'Count of clicks')\n\nclicks %>% \n  ggplot(mapping = aes(x = clicks_3dd, y = q2_error_cm)) + \n  geom_point(position = position_jitter(width = 1/5, height = 0), alpha = 1/10) + \n  geom_smooth() +\n  # scale_x_log10() +\n  theme_bw() + \n  theme(aspect.ratio = 1) + \n  labs(x = 'Number of WebGL clicks',\n       y = 'log2(|Error|+1/8)')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Histogram](index_files/figure-pdf/fig-clicks3dd-1.pdf){#fig-clicks3dd-1 fig-scap='Interactions with digital 3D heatmaps' width=90%}\n:::\n\n::: {.cell-output-display}\n![WebGL clicks vs. Error](index_files/figure-pdf/fig-clicks3dd-2.pdf){#fig-clicks3dd-2 fig-scap='Interactions with digital 3D heatmaps' width=90%}\n:::\n\nParticipant interactions with the digital 3D heatmaps.\n:::\n\n::: {#fig-slider-clicks .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nres_q2_filtered %>% \n  ggplot(mapping = aes(x = slider_clicks)) + \n  geom_histogram(binwidth = 1, fill = '#1a80bb', color = 'black') + \n  theme_bw() + \n  labs(x = 'Number of slider clicks', y = 'Count') + \n  theme(aspect.ratio = 1)\n\nres_q2_filtered %>% \n  ggplot(mapping = aes(x = slider_clicks, y = q2_error_cm)) + \n  geom_point(position = position_jitter(width = 1/5, height = 0), alpha = 1/10) +\n  geom_smooth() +\n  labs(x = 'Number of slider clicks', y = 'log2(|Error|+1/8') + \n  theme_bw() + \n  theme(aspect.ratio = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Histogram](index_files/figure-pdf/fig-slider-clicks-1.pdf){#fig-slider-clicks-1 fig-scap='Slider interaction behavior and error' width=90%}\n:::\n\n::: {.cell-output-display}\n![Slider clicks vs. Error](index_files/figure-pdf/fig-slider-clicks-2.pdf){#fig-slider-clicks-2 fig-scap='Slider interaction behavior and error' width=90%}\n:::\n\nParticipant interactions with the slider. \n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nres_q2_filtered %>% \n  ggplot(mapping = aes(x = slider_start, y = user_slider)) + \n  geom_point(alpha = 1/10) +\n  labs(x = 'Initial slider position', y = 'Submitted slider value') + \n  geom_smooth() +\n  theme_bw() + \n  theme(aspect.ratio = 1/1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Effect of initial slider position on the submitted slider value. ](index_files/figure-pdf/fig-slider-start-1.pdf){#fig-slider-start fig-pos='H' fig-scap='Initial slider position versus submitted value'}\n:::\n:::\n\n\n\n\n## Discussion and Conclusion\n\nOur study was designed to test the numerical estimation of ratios in 2D and 3D heatmaps rendered in digital and physical environments. The current state of tangible statistical graphics is limited mainly to tactile displays, whereas 3D printed statistical graphics are largely unexplored. We found that when the third dimension is conveying meaningful information, the heights of 3D heatmaps had smaller errors than the color gradient of 2D heatmaps. No differences were detected between the digital and physical 3D heatmaps, which is perhaps attributed to the exact one-to-one design relationship between the digital display and the 3D printed chart. These findings were consistent across multiple levels of fitted models and participant filtering, which reaffirms our belief that 3D charts have value when meaningfully using all three dimensions.\n\nAn interesting observation from the stimuli pairs and dataset interaction was from the non-detectable differences. We note that no differences were detected across datasets for a given stimuli pair. While not explicitly tested in our experiment, there have been previous studies that have investigated and found the behavior of neighboring values to have an effect [@zacks1998; @vanderplasSignsSineIllusion2015]. This effect would be worth exploring in future studies with 3D heatmaps. Another concern we had when designing our experiment was the lack of direct translation from color scales to heights. The differences between stimuli pairs of identical ratios were non-detectable, which alleviates this concern for future studies. However, this effect would likely be important to consider if assessing just noticeable differences [@luModelingJustNoticeable2022; @zhangJustNoticeableDifference2023].\n\nWhile our hypothesis that 3D-printed heatmaps would outperform digital 2D and 3D heatmaps in numerical estimations of ratios was not supported, we were able to show that 3D charts may have a place in the analysis of data. When the third dimension is used to display information, the mapping of that dimension to height provides better ratio estimations than a color gradient scale. This result has been observed previously in digital 3D heatmaps [@barfield1989; @kraus2020], and our findings suggests that this may hold for physical 3D heatmaps.\n\n## Appendix\n\nIn this section, we include multiple models for the transparency of model selection. Visual inspections of participant responses indicate that several participants clearly did not follow instructions by either using alternate estimation strategies or by carelessly responding [@fig-q1-eda]. While we should take these cases into consideration, there is no singular solution to suggest a \"best\" model [@jasoIdentificationCarelessResponding2021; @ward2023]. Our purpose for including these alternate models is to examine model sensitivity to results through various levels of participant and response filtering.\n\nFor each model, we exclude stimuli pair 5. In theory, participants who answer this question correctly will select that both values are the same and move the slider to 100. From the included participants, as described in @sec-remove-random-categories, virtually all participants who put the slider at 100 answered the first question correctly. However, nearly 60 percent of responses indicated that the values were the same in the first question but did not move the slider to 100. Several factors could have attributed to this, such as slider sensitivity or participants using alternate estimation strategies. Rather than correcting what we think participants should have answered, we removed this stimuli pair and motivate future research into \"just noticeable differences\" for 3D heatmaps.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfilter.labs <- c('Included Participants', 'Excluded Participants')\nnames(infilter.labs) <- c(TRUE, FALSE)\n\nres_q2 %>% \n  filter(pair_id == 5) %>% \n  mutate(infilter = user_id %in% res_q2_filtered$user_id) %>% \n  group_by(q1_correct = user_larger == true_larger,\n           slider100 = user_slider == 100,\n           infilter) %>% \n  count() %>% \n  arrange(infilter, q1_correct) %>% \n  ggplot(mapping = aes(x = slider100, y = n, fill = q1_correct)) + \n  geom_col(position = position_dodge()) + \n  geom_text(aes(label = n, y = n+8), position = position_dodge(width = 1),\n            size = 3) + \n  labs(x = 'Slider position', y = 'Count',\n       fill = 'Correct solution\\nto Q1?') +\n  facet_wrap(~infilter, labeller = labeller(infilter = infilter.labs)) + \n  scale_fill_manual(labels = c(\"No\", \"Yes\"),\n                    values = c('#b8b8b8', '#1a80bb')) +\n  scale_x_discrete(labels = c('Not at 100', 'At 100')) + \n  theme_bw() + \n  theme(aspect.ratio = 1, legend.position = 'bottom')\n```\n\n::: {.cell-output-display}\n![Counts of response behavior for Stimuli Pair 5. This pair had identical values, which means that true solutions indicates marking that they were the same value and positioning the slider at 100.](index_files/figure-pdf/fig-pair5-issues-1.pdf){#fig-pair5-issues fig-pos='H' fig-scap='Response behavior for identical-value stimuli pair'}\n:::\n:::\n\n\n\n\nThere are multiple levels of participant and response filtering that we considered. For participant-level filtering, we consider the following levels: (1) no participant filtering and (2) remove suspected random guessers. The process of (2) was described in @sec-remove-random-categories. Filtering individual responses is a straightforward process, where we considered (i) include all responses, and (ii) remove responses with incorrect Q1 solutions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Format: mod_(participant)_(response)\n\n# All participants\nmod_all_all <- lmer(q2_error_cm ~ set*media*pair_id + (1|user_id:block/set:media),\n     data = filter(res_q2, pair_id != 5))\nmod_all_q1 <- lmer(q2_error_cm ~ set*media*pair_id + (1|user_id:block/set:media),\n     data = filter(res_q2, pair_id != 5 & user_larger == true_larger))\n\n# Filtered participants\nmod_q1_all <- lmer(q2_error_cm ~ set*media*pair_id + (1|user_id:block/set:media),\n     data = filter(res_q2_filtered, pair_id != 5))\nmod_q1_q1 <- lmer(q2_error_cm ~ set*media*pair_id + (1|user_id:block/set:media),\n     data = filter(res_q2_filtered, pair_id != 5 & user_larger == true_larger))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  car::Anova(mod_all_all, type = 3, test = 'F') %>% \n  data.frame() %>% \n  janitor::clean_names() %>% \n  rownames_to_column('effect'),\n  car::Anova(mod_all_q1, type = 3, test = 'F') %>% \n  data.frame() %>% \n  janitor::clean_names() %>% \n  rownames_to_column('effect'),\n  car::Anova(mod_q1_all, type = 3, test = 'F') %>% \n  data.frame() %>% \n  janitor::clean_names() %>% \n  rownames_to_column('effect'),\n  car::Anova(mod_q1_q1, type = 3, test = 'F') %>% \n  data.frame() %>% \n  janitor::clean_names() %>% \n  rownames_to_column('effect'),\n  .id = 'model'\n) %>% \n  filter(effect != '(Intercept)') %>% \n  select(model, effect, pr_f) %>% \n  pivot_wider(names_from = effect, values_from = pr_f) %>% \n  mutate(across(where(is.numeric), round, 3)) %>% \n  mutate(model = case_when(\n    model=='1' ~ 'All participants, all responses',\n    model=='2' ~ 'All participants, Q1 correct',\n    model=='3' ~ 'Filtered participants, all responses',\n    model=='4' ~ 'Filtered participants, Q1 correct'\n  )) %>% \n  column_to_rownames('model') %>% \n  t() %>% \n  as.data.frame() %>% \n  rownames_to_column('Term') %>% \n  kable(caption = 'ANOVA Table p-values for model terms', digits = 3, booktabs = T,\n        label = 'tbl-all-models-anova')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `mutate()`.\ni In argument: `across(where(is.numeric), round, 3)`.\nCaused by warning:\n! The `...` argument of `across()` is deprecated as of dplyr 1.1.0.\nSupply arguments directly to `.fns` through an anonymous function instead.\n\n  # Previously\n  across(a:b, mean, na.rm = TRUE)\n\n  # Now\n  across(a:b, \\(x) mean(x, na.rm = TRUE))\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: ANOVA Table p-values for model terms\n\n|Term              | All participants, all responses| All participants, Q1 correct| Filtered participants, all responses| Filtered participants, Q1 correct|\n|:-----------------|-------------------------------:|----------------------------:|------------------------------------:|---------------------------------:|\n|set               |                           0.340|                        0.705|                                0.939|                             0.735|\n|media             |                           0.010|                        0.018|                                0.035|                             0.041|\n|pair_id           |                           0.244|                        0.333|                                0.089|                             0.063|\n|set:media         |                           0.297|                        0.711|                                0.543|                             0.669|\n|set:pair_id       |                           0.003|                        0.145|                                0.001|                             0.073|\n|media:pair_id     |                           0.815|                        0.740|                                0.982|                             0.968|\n|set:media:pair_id |                           0.489|                        0.764|                                0.255|                             0.833|\n\n\n:::\n\n```{.r .cell-code}\n# car::Anova(mod_all_all, type = 3, test = 'F')\n# car::Anova(mod_all_q1, type = 3, test = 'F')\n# car::Anova(mod_q1_all, type = 3, test = 'F')\n# car::Anova(mod_q1_q1, type = 3, test = 'F')\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nem_all_all <- emmeans(mod_all_all, ~media+set+pair_id, pbkrtest.limit = 5800)\nem_all_q1 <- emmeans(mod_all_q1, ~media+set+pair_id, pbkrtest.limit = 5800)\nem_q1_all <- emmeans(mod_q1_all, ~media+set+pair_id, pbkrtest.limit = 5800)\nem_q1_q1 <- emmeans(mod_q1_q1, ~media+set+pair_id, pbkrtest.limit = 5800)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  data.frame(em_all_all),\n  data.frame(em_all_q1),\n  data.frame(em_q1_all),\n  data.frame(em_q1_q1),\n  .id = 'model'\n) %>% \n  mutate(model = case_when(\n    model=='1' ~ 'All participants, all responses',\n    model=='2' ~ 'All participants, Q1 correct',\n    model=='3' ~ 'Filtered participants, all responses',\n    model=='4' ~ 'Filtered participants, Q1 correct'\n  )) %>% \n  ggplot(mapping = aes(x = media, y = emmean, color = model, group = model)) + \n  geom_point(size = 1) + \n  geom_line() + \n  facet_wrap(~set+pair_id, labeller = label_both) +\n  # facet_grid(set ~ pair_id) + \n  # facet_grid(pair_id ~ set) + \n  theme_bw() +\n  guides(color=guide_legend(nrow=2,byrow=TRUE)) + \n  theme(aspect.ratio = 1/2,\n        legend.position = 'bottom')\n```\n\n::: {.cell-output-display}\n![Interaction plots for media type and response filtering, facetted by stimuli pair and dataset.](index_files/figure-pdf/fig-model-int1-1.pdf){#fig-model-int1 fig-pos='H' fig-scap='Media by filtering interaction effects'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  data.frame(em_all_all),\n  data.frame(em_all_q1),\n  data.frame(em_q1_all),\n  data.frame(em_q1_q1),\n  .id = 'model'\n) %>% \n  mutate(model = case_when(\n    model=='1' ~ 'All participants, all responses',\n    model=='2' ~ 'All participants, Q1 correct',\n    model=='3' ~ 'Filtered participants, all responses',\n    model=='4' ~ 'Filtered participants, Q1 correct'\n  )) %>% \n  ggplot(mapping = aes(x = set, y = emmean, color = model, group = model)) + \n  geom_point(size = 1) + \n  geom_line() + \n  facet_grid(media~pair_id, labeller = label_both) +\n  # facet_grid(set ~ pair_id) + \n  # facet_grid(pair_id ~ set) + \n  theme_bw() +\n  guides(color=guide_legend(nrow=2,byrow=TRUE)) + \n  theme(aspect.ratio = 1/1,\n        strip.text.y = element_text(size = 6),\n        legend.position = 'bottom')\n```\n\n::: {.cell-output-display}\n![Interaction plots for dataset and response filtering, facetted by stimuli pair and media type.](index_files/figure-pdf/fig-model-int2-1.pdf){#fig-model-int2 fig-pos='H' fig-scap='Data set by filtering interaction effects'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  data.frame(em_all_all),\n  data.frame(em_all_q1),\n  data.frame(em_q1_all),\n  data.frame(em_q1_q1),\n  .id = 'model'\n) %>% \n  mutate(model = case_when(\n    model=='1' ~ 'All participants, all responses',\n    model=='2' ~ 'All participants, Q1 correct',\n    model=='3' ~ 'Filtered participants, all responses',\n    model=='4' ~ 'Filtered participants, Q1 correct'\n  )) %>% \n  ggplot(mapping = aes(x = pair_id, y = emmean, color = model, group = model)) + \n  geom_point(size = 1) + \n  geom_line() + \n  facet_grid(set~media, labeller = label_both) +\n  # facet_grid(set ~ pair_id) + \n  # facet_grid(pair_id ~ set) + \n  theme_bw() +\n  guides(color=guide_legend(nrow=2,byrow=TRUE)) + \n  theme(aspect.ratio = 1/1,\n        # strip.text.y = element_text(size = 6),\n        legend.position = 'bottom')\n```\n\n::: {.cell-output-display}\n![Interaction plots for stimuli pairs and response filtering, facetted by dataset and media type.](index_files/figure-pdf/fig-model-int3-1.pdf){#fig-model-int3 fig-pos='H' fig-scap='Stimuli pair by filtering interaction effects'}\n:::\n:::\n\n\n\n\n\\newpage\n\n:::{.callout-note}\n\nThis paragraph is pushed to a new page since the ANOVA table p-values is causing formatting issues\n\n:::\n\nVisualizations of the simple effects for media types, datasets, and stimuli pairs (@fig-model-int1, @fig-model-int2, @fig-model-int3) shows that the difference between participant filtering is mostly a linear shift in log error. Removing participants deemed to be random guessers tended to have smaller errors than including all participants. The shift is less prevalent across participant filters when filtering out incorrect responses to the first question in each trial. This, in addition to the p-values from @tbl-all-models-anova, suggests that our sample size was large enough to counteract effects from careless respondents.\n\nWe also attempted to fit Gaussian mixture models to the submitted responses using the `flexmix` package [@flexmix] to account for careless respondents [@jasoIdentificationCarelessResponding2021]. However, these models only reliably detected a small subset of participants who were would be considered high performers. That is, participants who had a near 1:1 relationship with the ratio estimations strategy and small variation. Visual inspections of the mixture model components did not provide reliable classifications of estimation strategies, so we opted to exclude mixture models from consideration.\n\n### Generalized Additive Model\n\nIn addition to our parametric methods, we also present the results of a generalized additive model [@hastie2017generalized]. Here, we define the model similarly to the parametric models, but replace stimuli pair identifiers with their respective numerical ratio value. Thin-plate regression splines in the generalized additive model account for nonlinearity which could alleviate issues due to different estimation strategies. The formal statistical model is as follows:\n\n$$\ny=\\mu+S_i\\times M_j + s_i^S(R)+s_j^M(R)+P_m+\\epsilon\n$$ {#eq-gam}\n\nwhere\n\n-   $y=\\log_2(|\\text{Error}|+1/8)$\n\n-   $S_i\\times M_j$ is the fixed effects for main effect and two-way interactions of dataset $S_i$ and media type $M_j$\n\n-   $S_i^S(R)$ is a thin-plate spline function for ratio accounting for dataset\n\n-   $S_j^M(R)$ is a thin-plate spline function for ratio accounting for media type\n\n-   $P_m$ is the random effect of the $m^{th}$ participant\n\n-   $\\epsilon$ is random error\n\nA generalized additive model was fit using the `mgcv` package [@mgcv] on the entire dataset and the filtered dataset. The data for these models remove stimuli pair 5 and incorrect responses to the initial question. In both cases, results of the generalized additive models suggest that the 2D heatmaps have larger errors than the 3D heatmaps, with no differences detected between the digital and physical heatmaps [@tbl-gam-emmeans; @tbl-gam-diffs].\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GAM\nlibrary(mgcv)\nlibrary(gratia)\nmod_gam <- gam(\n  q2_error_cm ~ \n    set*media + \n    s(target_ratio, k = 4, by = media) + \n    s(target_ratio, k = 4, by = set) + \n    s(user_id, bs='re'),\n  method = 'REML',\n  data = filter(res_q2, pair_id != 5 & user_larger == true_larger) %>% \n    mutate(set = factor(set),\n           media = factor(media),\n           user_id = factor(user_id))\n)\ngam_sum <- summary(mod_gam)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_gam_flt <- gam(\n  q2_error_cm ~ \n    set*media + \n    s(target_ratio, k = 4, by = media) + \n    s(target_ratio, k = 4, by = set) + \n    s(user_id, bs='re'),\n  method = 'REML',\n  data = filter(res_q2_filtered, pair_id != 5 & user_larger == true_larger) %>% \n    mutate(set = factor(set),\n           media = factor(media),\n           user_id = factor(user_id))\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngam_sum <- summary(mod_gam)\ngam_sum2 <- summary(mod_gam_flt)\n\ngam_sum$p.table %>% knitr::kable(digits = 3, caption = \"Parametric coefficients in gam model with all participants.\", label = \"gam-param1\", booktabs = T)\n```\n\n::: {.cell-output-display}\n\n\nTable: Parametric coefficients in gam model with all participants.\n\n|                 | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:----------------|--------:|----------:|-------:|------------------:|\n|(Intercept)      |    3.773|      0.083|  45.613|              0.000|\n|setset2          |    0.014|      0.080|   0.172|              0.863|\n|media3dd         |   -0.317|      0.077|  -4.094|              0.000|\n|media3dp         |   -0.389|      0.089|  -4.359|              0.000|\n|setset2:media3dd |    0.018|      0.110|   0.163|              0.871|\n|setset2:media3dp |    0.078|      0.124|   0.630|              0.529|\n\n\n:::\n\n```{.r .cell-code}\ngam_sum$s.table %>% as.data.frame() %>% \n  mutate(Smooth = rownames(.),\n         Smooth = str_replace(Smooth, \"ratio_prop\", \"Ratio\")) %>%\n  select(Smooth, everything()) %>%\n  knitr::kable(digits = 3, row.names = F, caption = \"Approximate significance of smooth terms in gam mode with all participants.\", label = \"gam-smooth1\", booktabs = T)\n```\n\n::: {.cell-output-display}\n\n\nTable: Approximate significance of smooth terms in gam mode with all participants.\n\n|Smooth                   |     edf|  Ref.df|     F| p-value|\n|:------------------------|-------:|-------:|-----:|-------:|\n|s(target_ratio):media2dd |   1.002|   1.003| 0.058|   0.813|\n|s(target_ratio):media3dd |   1.972|   2.350| 1.476|   0.200|\n|s(target_ratio):media3dp |   1.047|   1.428| 1.612|   0.268|\n|s(target_ratio):setset1  |   1.005|   1.009| 0.650|   0.422|\n|s(target_ratio):setset2  |   1.022|   1.042| 0.165|   0.719|\n|s(user_id)               | 217.826| 258.000| 6.423|   0.000|\n\n\n:::\n\n```{.r .cell-code}\ngam_sum$p.table %>% knitr::kable(digits = 3, caption = \"Parametric coefficients in gam model without random guessers.\", label = \"gam-param2\", booktabs = T)\n```\n\n::: {.cell-output-display}\n\n\nTable: Parametric coefficients in gam model without random guessers.\n\n|                 | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:----------------|--------:|----------:|-------:|------------------:|\n|(Intercept)      |    3.773|      0.083|  45.613|              0.000|\n|setset2          |    0.014|      0.080|   0.172|              0.863|\n|media3dd         |   -0.317|      0.077|  -4.094|              0.000|\n|media3dp         |   -0.389|      0.089|  -4.359|              0.000|\n|setset2:media3dd |    0.018|      0.110|   0.163|              0.871|\n|setset2:media3dp |    0.078|      0.124|   0.630|              0.529|\n\n\n:::\n\n```{.r .cell-code}\ngam_sum$s.table %>% as.data.frame() %>% \n  mutate(Smooth = rownames(.),\n         Smooth = str_replace(Smooth, \"ratio_prop\", \"Ratio\")) %>%\n  select(Smooth, everything()) %>%\n  knitr::kable(digits = 3, row.names = F, caption = \"Approximate significance of smooth terms in gam model without random guessers.\", label = \"gam-smooth2\", booktabs = T)\n```\n\n::: {.cell-output-display}\n\n\nTable: Approximate significance of smooth terms in gam model without random guessers.\n\n|Smooth                   |     edf|  Ref.df|     F| p-value|\n|:------------------------|-------:|-------:|-----:|-------:|\n|s(target_ratio):media2dd |   1.002|   1.003| 0.058|   0.813|\n|s(target_ratio):media3dd |   1.972|   2.350| 1.476|   0.200|\n|s(target_ratio):media3dp |   1.047|   1.428| 1.612|   0.268|\n|s(target_ratio):setset1  |   1.005|   1.009| 0.650|   0.422|\n|s(target_ratio):setset2  |   1.022|   1.042| 0.165|   0.719|\n|s(user_id)               | 217.826| 258.000| 6.423|   0.000|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nem_gam1 <- emmeans(mod_gam, ~media|set)\nem_gam2 <- emmeans(mod_gam_flt, ~media|set)\n\nbind_rows(\n  em_gam1 %>% data.frame() %>% mutate(flt = 'All participants'),\n  em_gam2 %>% data.frame() %>% mutate(flt = 'Random guessers removed')\n) %>% \n  select(`Data filtering` = flt, set, emmean:upper.CL) %>% \n  kbl(caption = 'Estimated marginal means for generalized additive model', digits = 3,\n      booktabs = T, label = 'tbl-gam-emmeans') %>% \n  collapse_rows()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:tbl-gam-emmeans}Estimated marginal means for generalized additive model}\n\\centering\n\\begin{tabular}[t]{llrrrrr}\n\\toprule\nData filtering & set & emmean & SE & df & lower.CL & upper.CL\\\\\n\\midrule\n &  & 3.773 & 0.083 &  & 3.611 & 3.936\\\\\n\\cmidrule{3-4}\n\\cmidrule{6-7}\n &  & 3.532 & 0.090 &  & 3.356 & 3.709\\\\\n\\cmidrule{3-4}\n\\cmidrule{6-7}\n & \\multirow{-3}{*}[1\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash set1} & 3.493 & 0.105 &  & 3.286 & 3.700\\\\\n\\cmidrule{2-4}\n\\cmidrule{6-7}\n &  & 3.788 & 0.083 &  & 3.625 & 3.951\\\\\n\\cmidrule{3-4}\n\\cmidrule{6-7}\n &  & 3.565 & 0.091 &  & 3.387 & 3.742\\\\\n\\cmidrule{3-4}\n\\cmidrule{6-7}\n\\multirow{-6}{*}[2.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash All participants} & \\multirow{-3}{*}[1\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash set2} & 3.586 & 0.106 & \\multirow{-6}{*}[2.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedleft\\arraybackslash 3729.128} &  & 3.794\\\\\n\\cmidrule{1-5}\n\\cmidrule{7-7}\n &  & 3.593 & 0.109 &  & \\multirow{-2}{*}[0.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedleft\\arraybackslash 3.378} & 3.807\\\\\n\\cmidrule{3-4}\n\\cmidrule{6-7}\n &  & 3.150 & 0.107 &  & 2.939 & 3.360\\\\\n\\cmidrule{3-4}\n\\cmidrule{6-7}\n & \\multirow{-3}{*}[1\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash set1} & 3.199 & 0.115 &  & 2.973 & 3.425\\\\\n\\cmidrule{2-4}\n\\cmidrule{6-7}\n &  & 3.693 & 0.109 &  & 3.479 & 3.906\\\\\n\\cmidrule{3-4}\n\\cmidrule{6-7}\n &  & 3.361 & 0.108 &  & 3.149 & 3.574\\\\\n\\cmidrule{3-4}\n\\cmidrule{6-7}\n\\multirow{-6}{*}[2.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash Random guessers removed} & \\multirow{-3}{*}[1\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash set2} & 3.310 & 0.116 & \\multirow{-6}{*}[2.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedleft\\arraybackslash 2814.776} & 3.081 & 3.538\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  pairs(em_gam1) %>% data.frame() %>% mutate(flt = 'All participants'),\n  pairs(em_gam2) %>% data.frame() %>% mutate(flt = 'Random guessers removed')\n) %>% \n  select(`Data filtering` = flt, set, contrast, estimate:p.value) %>% \n  kbl(caption = 'Pairwise differences for generalized additive model', digits = 3,\n      booktabs = T, label = 'tbl-gam-diffs') %>% \n  collapse_rows()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\n\\caption{\\label{tab:tbl-gam-diffs}Pairwise differences for generalized additive model}\n\\centering\n\\begin{tabular}[t]{lllrrrrr}\n\\toprule\nData filtering & set & contrast & estimate & SE & df & t.ratio & p.value\\\\\n\\midrule\n &  & 2dd - 3dd & 0.241 & 0.088 &  & 2.736 & 0.017\\\\\n\\cmidrule{3-5}\n\\cmidrule{7-8}\n &  & 2dd - 3dp & 0.280 & 0.103 &  & 2.711 & 0.018\\\\\n\\cmidrule{3-5}\n\\cmidrule{7-8}\n & \\multirow{-3}{*}[1\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash set1} & 3dd - 3dp & 0.039 & 0.109 &  & 0.361 & 0.931\\\\\n\\cmidrule{2-5}\n\\cmidrule{7-8}\n &  & 2dd - 3dd & 0.223 & 0.089 &  & 2.516 & 0.032\\\\\n\\cmidrule{3-5}\n\\cmidrule{7-8}\n &  & 2dd - 3dp & 0.202 & 0.104 &  & 1.940 & 0.128\\\\\n\\cmidrule{3-5}\n\\cmidrule{7-8}\n\\multirow{-6}{*}[2.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash All participants} & \\multirow{-3}{*}[1\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash set2} & 3dd - 3dp & -0.021 & 0.110 & \\multirow{-6}{*}[2.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedleft\\arraybackslash 3729.128} & -0.192 & 0.980\\\\\n\\cmidrule{1-8}\n &  & 2dd - 3dd & 0.443 & 0.091 &  & 4.868 & \\\\\n\\cmidrule{3-5}\n\\cmidrule{7-7}\n &  & 2dd - 3dp & 0.394 & 0.100 &  & 3.925 & \\multirow{-2}{*}{\\raggedleft\\arraybackslash 0.000}\\\\\n\\cmidrule{3-5}\n\\cmidrule{7-8}\n & \\multirow{-3}{*}[1\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash set1} & 3dd - 3dp & -0.049 & 0.099 &  & -0.499 & 0.872\\\\\n\\cmidrule{2-5}\n\\cmidrule{7-8}\n &  & 2dd - 3dd & 0.331 & 0.092 &  & 3.585 & \\\\\n\\cmidrule{3-5}\n\\cmidrule{7-7}\n &  & 2dd - 3dp & 0.383 & 0.102 &  & 3.757 & \\multirow{-2}{*}{\\raggedleft\\arraybackslash 0.001}\\\\\n\\cmidrule{3-5}\n\\cmidrule{7-8}\n\\multirow{-6}{*}[2.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash Random guessers removed} & \\multirow{-3}{*}[1\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedright\\arraybackslash set2} & 3dd - 3dp & 0.052 & 0.100 & \\multirow{-6}{*}[2.5\\dimexpr\\aboverulesep+\\belowrulesep+\\cmidrulewidth]{\\raggedleft\\arraybackslash 2814.776} & 0.521 & 0.861\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n\n\\newpage\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}